package net.ausiasmarch.bean;
// Generated 23-ene-2015 16:40:35 by Hibernate Tools 4.3.1



/**
 * Coche generated by hbm2java
 */
public class Coche  implements java.io.Serializable {


     private Integer id;
     private String marca;
     private String modelo;

    public Coche() {
    }

    public Coche(String marca, String modelo) {
       this.marca = marca;
       this.modelo = modelo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }




}


